package attendancemanagementsystem2;

public class Section2 extends AttendanceManagementSystem2 {    
    static void mainfunc2(){
        Dets Section2_1 = new Dets (201 , 19 , "Hazel-Mae" , "Blanquera" , "Albino" , "Female" , "BSIT2", "N/A");
        Dets Section2_2 = new Dets (202 , 19 , "Jinel-Hanz" , "Arimas" , "Anacite" , "Male" , "BSIT2", "N/A");
        Dets Section2_3 = new Dets (203 , 20 , "Selvester" , "Baldon" , "Apor" , "Male" , "BSIT2", "N/A");
        Dets Section2_4 = new Dets (204 , 20 , "Venz-Jan" , "Achas" , "Cabonegro" , "Male" , "BSIT2" , "N/A");
        Dets Section2_5 = new Dets (205 , 20 , "Beverly" , "Aba" , "Canoy" , "Male" , "BSIT2", "N/A");
        Dets Section2_6 = new Dets (206 , 20 , "Angelo" , "Carillo" , "Castro" , "Male" , "BSIT2", "N/A");
        Dets Section2_7 = new Dets (207 , 20 , "Ernest-Dale" , "Siglos" , "Carton" , "Male" , "BSIT2", "N/A");
        Dets Section2_8 = new Dets (208 , 20 , "Althea-Dela" , "Vega" , "Dewites" , "Male" , "BSIT2", "N/A");
        Dets Section2_9 = new Dets (209 , 20 , "Karl-John" , "Regunda" , "Dutosme" , "Male" , "BSIT2", "N/A");
        Dets Section2_10 = new Dets (210 , 20 , "Kharlo" , "Castro" , "Edulan" , "Male" , "BSIT2", "N/A");
        Dets Section2_11 = new Dets (211 , 20 , "Joejette" , "Olano" , " Ferrariz" , "Male" , "BSIT2" , "N/A");
        Dets Section2_12 = new Dets (212 , 20 , "Shan-Ii" , "Maghopoy" , "Gorra" , "Male" , "BSIT2", "N/A");
        Dets Section2_13 = new Dets (213 , 20 , "Joshua" , "Daguno" , "Gumahad" , "Male" , "BSIT2" ,"N/A");
        Dets Section2_14 = new Dets (214 , 21 , "Dexter" , "Palarca" , "Maghanoy" , "Male" , "BSIT2", "N/A");
        Dets Section2_15 = new Dets (215 , 21 , "Brecht" , "Pagtalunan" , "Marquita" , "Male" , "BSIT2", "N/A");
        Dets Section2_16 = new Dets (216 , 21 , "Andrie-Mark" , "Tudtod" , "Matildo" , "Male" , "BSIT2", "N/A");
        Dets Section2_17 = new Dets (217 , 20 , "Joemari" , "Uba" , "Obrial" , "Male" , "BSIT2" , "N/A");
        Dets Section2_18 = new Dets (218 , 20 , "Charls-John" , "Vargas" , "Opiso" , "Male" , "BSIT2", "N/A");
        Dets Section2_19 = new Dets (219 , 21 , "Feliciano-Sherdy" , "Egoc" , "Pagaran" , "Male" , "BSIT2" , "N/A");
        Dets Section2_20 = new Dets (220 , 20 , "Rosemari" , "Kilat" , "Roque" , "Female" , "BSIT2" , "N/A");
        Dets Section2_21 = new Dets (221 , 20 , "Nimriel" , "Longhas" , "Sigua" , "Male" , "BSIT2", "N/A");
        Dets Section2_22 = new Dets (222 , 20 , "Kizziah-Zandra" , "Francisco" , "Tajor" , "Female" , "BSIT2", "N/A");
        Dets Section2_23 = new Dets (223 , 20 , "Andrew-Albert" , "Ganaden" , "Talaboc" , "Male" , "BSIT2" , "N/A");
        Dets Section2_24 = new Dets (224 , 20 , "Herod-Jan" , "Barrientos" , "Tan" , "Male" , "BSIT2", "N/A");
        Dets Section2_25 = new Dets (225 , 20 , "Rhon-Kenneth" , "N/A" , "Trazo" , "Male" , "BSIT2" , "N/A");
        
        UniqueID uid1 = new UniqueID(201);
        UniqueID uid2 = new UniqueID(202);
        UniqueID uid3 = new UniqueID(203);
        UniqueID uid4 = new UniqueID(204);
        UniqueID uid5 = new UniqueID(205);
        UniqueID uid6 = new UniqueID(206);
        UniqueID uid7 = new UniqueID(207);
        UniqueID uid8 = new UniqueID(208);
        UniqueID uid9 = new UniqueID(209);
        UniqueID uid10 = new UniqueID(210);
        UniqueID uid11 = new UniqueID(211);
        UniqueID uid12 = new UniqueID(212);
        UniqueID uid13 = new UniqueID(213);
        UniqueID uid14 = new UniqueID(214);
        UniqueID uid15 = new UniqueID(215);
        UniqueID uid16 = new UniqueID(216);
        UniqueID uid17 = new UniqueID(217);
        UniqueID uid18 = new UniqueID(218);
        UniqueID uid19 = new UniqueID(219);
        UniqueID uid20 = new UniqueID(220);
        UniqueID uid21 = new UniqueID(221);
        UniqueID uid22 = new UniqueID(222);
        UniqueID uid23 = new UniqueID(223);
        UniqueID uid24 = new UniqueID(224);
        UniqueID uid25 = new UniqueID(225);
        
	studList.add(Section2_1);
        uniqueid.add(uid1);
	studList.add(Section2_2);
        uniqueid.add(uid2);
	studList.add(Section2_3);
        uniqueid.add(uid3);
	studList.add(Section2_4);
        uniqueid.add(uid4);
	studList.add(Section2_5);
        uniqueid.add(uid5);
	studList.add(Section2_6);
        uniqueid.add(uid6);
	studList.add(Section2_7);
        uniqueid.add(uid7);
	studList.add(Section2_8);
        uniqueid.add(uid8);
	studList.add(Section2_9);
        uniqueid.add(uid9);
	studList.add(Section2_10);
        uniqueid.add(uid10);
	studList.add(Section2_11);
        uniqueid.add(uid11);
	studList.add(Section2_12);
        uniqueid.add(uid12);
	studList.add(Section2_13);
        uniqueid.add(uid13);
	studList.add(Section2_14);
        uniqueid.add(uid14);
	studList.add(Section2_15);
        uniqueid.add(uid15);
	studList.add(Section2_16);
        uniqueid.add(uid16);
	studList.add(Section2_17);
        uniqueid.add(uid17);
	studList.add(Section2_18);
        uniqueid.add(uid18);
	studList.add(Section2_19);
        uniqueid.add(uid19);
	studList.add(Section2_20);
        uniqueid.add(uid20);
	studList.add(Section2_21);
        uniqueid.add(uid21);
	studList.add(Section2_22);
        uniqueid.add(uid22);
	studList.add(Section2_23);
        uniqueid.add(uid23);
	studList.add(Section2_24);
        uniqueid.add(uid24);
        studList.add(Section2_25);
        uniqueid.add(uid25);
        choices();
    }
}