package attendancemanagementsystem2;

public class Section3 extends AttendanceManagementSystem2 {
    static void mainfunc3(){
        Dets Section3_1 = new Dets (301 , 20 , "Christian-Keith" , "Sapon" , "Abacahin" , "Male" , "BSIT3", "N/A");
        Dets Section3_2 = new Dets (302 , 21 , "Angelica" , "Felix" , "Alivio" , "Female" , "BSIT3", "N/A");
        Dets Section3_3 = new Dets (303 , 20 , "Mercy-Joy" , "Lastimosa" , "Arcayena" , "Female" , "BSIT3", "N/A");
        Dets Section3_4 = new Dets (304 , 20 , "Francis-Zoi" , "Pedronio" , "Auza" , "Male" ,"BSIT3", "N/A");
        Dets Section3_5 = new Dets (305 , 20 , "Syntechi" , "Sula" , "Balcon" , "Female" , "BSIT3", "N/A");
        Dets Section3_6 = new Dets (306 , 20 , "Christina" , "Balatero" , "Boborol" , "Female" ,"BSIT3", "N/A");
        Dets Section3_7 = new Dets (307 , 20 , "Glyde-Vinz" , "Abar" , "Burdas" , "Male" , "BIST3", "N/A");
        Dets Section3_8 = new Dets (308 , 20 , "Christian-Dave" , "Galapin" , "Cabiladas" , "Male" , "BSIT3", "N/A");
        Dets Section3_9 = new Dets (309 , 19 , "Clarence-Joel" , "Serdone" , "Camarillo" , "Male" , "BSIT3", "N/A");
        Dets Section3_10 = new Dets (310 , 20 , "Saint-Kaye" , "Ebajay" , "Cometa" , "Female" ,"BSIT3", "N/A");
        Dets Section3_11 = new Dets (311 , 22 , "Kide-Guile" , "Samoya" , "Compo" , "Male" , "BSIT3", "N/A");
        Dets Section3_12 = new Dets (312 , 19 , "Maria-Adora" , "Jaquilmac" , "Dumaog" , "Female" , "BSIT3", "N/A");
        Dets Section3_13 = new Dets (313 , 19 , "Justin-Clyde-Gerard" , "Singcahon" , "Ejida" , "Male" , "BSIT3", "N/A");
        Dets Section3_14 = new Dets (314 , 20 , "Ezra-Yuan" , "Atuel" , "Enguito" , "Male" , "BSIT3", "N/A");
        Dets Section3_15 = new Dets (315 , 20 , "Al-Juliana" , "Llemit" , "Hermoso" , "Female" ,"BSIT3", "N/A");
        Dets Section3_16 = new Dets (316 , 20 , "John-Rio" , "Manial" , "Mar" , "Male" , "BSIT3", "N/A");
        Dets Section3_17 = new Dets (317 , 20 , "John-paul" , "Daayata" , "Orencio" , "Male" , "BSIT3", "N/A");
        Dets Section3_18 = new Dets (318 , 20 , "May-Antonette" , "Ramos" , "Pabro" , "Female" ,"BSIT3", "N/A");
        Dets Section3_19 = new Dets (319 , 19 , "Kenneth-James" , "Oblad" , "Pacaldo" , "Male" , "BSIT3", "N/A");
        Dets Section3_20 = new Dets (320 , 20 , "Mark-Joseph" , "Quistadio" , "Palma" , "Male" , "BSIT3", "N/A");
        Dets Section3_21 = new Dets (321 , 20 , "Rycelle" , "Coming" , "Puruel" , "Female" , "BSIT3", "N/A");
        Dets Section3_22 = new Dets (322 , 20 , "Marlon-Kyell" , "Labial" , "Sajelan" , "Male" , "BSIT3", "N/A");
        Dets Section3_23 = new Dets (323 , 20 , "Ashley-Ivory" , "Jandayan" , "Tabaranza" , "Female" , "BSIT3", "N/A");
        Dets Section3_24 = new Dets (324 , 20 , "Ira Jake" , "Rebleza" , "Tato" , "Male" , "BSIT3", "N/A");
        Dets Section3_25 = new Dets (325 , 20 , "Sean-Gerick" , "N/A" , " Umlas", "Male" , "BSIT3", "N/A");
        
        UniqueID uid1 = new UniqueID(301);
        UniqueID uid2 = new UniqueID(302);
        UniqueID uid3 = new UniqueID(303);
        UniqueID uid4 = new UniqueID(304);
        UniqueID uid5 = new UniqueID(305);
        UniqueID uid6 = new UniqueID(306);
        UniqueID uid7 = new UniqueID(307);
        UniqueID uid8 = new UniqueID(308);
        UniqueID uid9 = new UniqueID(309);
        UniqueID uid10 = new UniqueID(310);
        UniqueID uid11 = new UniqueID(311);
        UniqueID uid12 = new UniqueID(312);
        UniqueID uid13 = new UniqueID(313);
        UniqueID uid14 = new UniqueID(314);
        UniqueID uid15 = new UniqueID(315);
        UniqueID uid16 = new UniqueID(316);
        UniqueID uid17 = new UniqueID(317);
        UniqueID uid18 = new UniqueID(318);
        UniqueID uid19 = new UniqueID(319);
        UniqueID uid20 = new UniqueID(320);
        UniqueID uid21 = new UniqueID(321);
        UniqueID uid22 = new UniqueID(322);
        UniqueID uid23 = new UniqueID(323);
        UniqueID uid24 = new UniqueID(324);
        UniqueID uid25 = new UniqueID(325);
        
        studList.add(Section3_1);
        uniqueid.add(uid1);
	studList.add(Section3_2);
        uniqueid.add(uid2);
	studList.add(Section3_3);
        uniqueid.add(uid3);
	studList.add(Section3_4);
        uniqueid.add(uid4);
	studList.add(Section3_5);
        uniqueid.add(uid5);
	studList.add(Section3_6);
        uniqueid.add(uid6);
	studList.add(Section3_7);
        uniqueid.add(uid7);
	studList.add(Section3_8);
        uniqueid.add(uid8);
	studList.add(Section3_9);
        uniqueid.add(uid9);
	studList.add(Section3_10);
        uniqueid.add(uid10);
	studList.add(Section3_11);
        uniqueid.add(uid11);
	studList.add(Section3_12);
        uniqueid.add(uid12);
	studList.add(Section3_13);
        uniqueid.add(uid13);
	studList.add(Section3_14);
        uniqueid.add(uid14);
	studList.add(Section3_15);
        uniqueid.add(uid15);
	studList.add(Section3_16);
        uniqueid.add(uid16);
	studList.add(Section3_17);
        uniqueid.add(uid17);
	studList.add(Section3_18);
        uniqueid.add(uid18);
	studList.add(Section3_19);
        uniqueid.add(uid19);
	studList.add(Section3_20);
        uniqueid.add(uid20);
	studList.add(Section3_21);
        uniqueid.add(uid21);
	studList.add(Section3_22);
        uniqueid.add(uid22);
	studList.add(Section3_23);
        uniqueid.add(uid23);
	studList.add(Section3_24);
        uniqueid.add(uid24);
        studList.add(Section3_25);
        uniqueid.add(uid25);
        choices();
    }
}