package attendancemanagementsystem2;
public class Section1 extends AttendanceManagementSystem2 {
    public static void main(){
        Dets Section1_1 = new Dets (101 , 19 , "Marvin" , "" , "" , "Male" , "BSIT1", "N/A");
        Dets Section1_2 = new Dets (102 , 20 , "Key-Mhare" , "" , "" , "Female" , "BSIT1", "N/A");
        Dets Section1_3 = new Dets (103 , 20 , "Mirah-Mea" , "" , "" , "Female" , "BSIT1", "N/A");
        Dets Section1_4 = new Dets (104 , 22 , "Hannah" , "" , "" , "Female" , "BSIT1", "N/A");
        Dets Section1_5 = new Dets (105 , 20 , "Duk" , "" , "" , "Male" , "BSIT1" , "N/A");
        Dets Section1_6 = new Dets (106 , 20 , "Joshua" , "" , "" , "Male" , "BSIT1", "N/A");
        Dets Section1_7 = new Dets (107 , 21 , "Earl-Justin" , "" , "" , "Male" , "BSIT1", "N/A");
        Dets Section1_8 = new Dets (108 , 21 , "Arnelle" , "" , "" , "Male" , "BSIT1", "N/A");
        Dets Section1_9 = new Dets (109 , 20 , "Joel" , "" , "" , "Male" , " BSIT1", "N/A");
        Dets Section1_10 = new Dets (110 , 20 , "Ruben" , "" , "" , "Male" , "BSIT1", "N/A");
        Dets Section1_11 = new Dets (111 , 20 , "Fitz-Gerard" , "" , "" , "Male" , "BSIT1", "N/A");
        Dets Section1_12 = new Dets (112 , 20 , "Jay-Anne" , "" , "" , "Female" , "BSIT1", "N/A");
        Dets Section1_13 = new Dets (113 , 23 , "Nick-Carter" , "" , "" , "Male" , "BSIT1", "N/A");
        Dets Section1_14 = new Dets (114 , 21 , "James-Ryan" , "" , "" , "Male" , "BSIT1", "N/A");
        Dets Section1_15 = new Dets (115 , 21 , "Shadrin-Jerome" , "" , "" , "Male" , "BSIT1", "N/A");
        Dets Section1_16 = new Dets (116 , 19 , "Karel" , "" , "" , "Female" , "BSIT1", "N/A");
        Dets Section1_17 = new Dets (117 , 19 , "Anadyl" , "" , "" , "Female" , "BSIT1", "N/A");
        Dets Section1_18 = new Dets (118 , 21 , "Hamza" , "" , "" , "Male" , "BSIT1" , "N/A");
        Dets Section1_19 = new Dets (119 , 20 , "Kert-Ice" , "" , "" , "Male" , "BSIT1", "N/A");
        Dets Section1_20 = new Dets (120 , 21 , "Jeric" , "" , "" , "Male" , "BSIT1", "N/A");
        Dets Section1_21 = new Dets (121 , 20 , "Angelo" , "" , "" , "Male" , "BSIT1" , "N/A");
        Dets Section1_22 = new Dets (122 , 19 , "May-Joy" , "" , "" , "Female" , "BSIT1" , "N/A");
        Dets Section1_23 = new Dets (123 , 19 , "Mary-Jane" , "" , "" , "Female" , "BSIT1", "N/A");
        Dets Section1_24 = new Dets (124 , 21 , "Jazerll" , "" , "" , "Male" , "BSIT1", "N/A");
        Dets Section1_25 = new Dets (125 , 20 , "John-Andrej" , "" , "" , "Male" , "BSIT1", "N/A");
        UniqueID uid1 = new UniqueID(101);
        UniqueID uid2 = new UniqueID(102);
        UniqueID uid3 = new UniqueID(103);
        UniqueID uid4 = new UniqueID(104);
        UniqueID uid5 = new UniqueID(105);
        UniqueID uid6 = new UniqueID(106);
        UniqueID uid7 = new UniqueID(107);
        UniqueID uid8 = new UniqueID(108);
        UniqueID uid9 = new UniqueID(109);
        UniqueID uid10 = new UniqueID(110);
        UniqueID uid11 = new UniqueID(111);
        UniqueID uid12 = new UniqueID(112);
        UniqueID uid13 = new UniqueID(113);
        UniqueID uid14 = new UniqueID(114);
        UniqueID uid15 = new UniqueID(115);
        UniqueID uid16 = new UniqueID(116);
        UniqueID uid17 = new UniqueID(117);
        UniqueID uid18 = new UniqueID(118);
        UniqueID uid19 = new UniqueID(119);
        UniqueID uid20 = new UniqueID(120);
        UniqueID uid21 = new UniqueID(121);
        UniqueID uid22 = new UniqueID(122);
        UniqueID uid23 = new UniqueID(123);
        UniqueID uid24 = new UniqueID(124);
        UniqueID uid25 = new UniqueID(125);
        studList.add(Section1_1);
        uniqueid.add(uid1);
	studList.add(Section1_2);
        uniqueid.add(uid2);
	studList.add(Section1_3);
        uniqueid.add(uid3);
	studList.add(Section1_4);
        uniqueid.add(uid4);
	studList.add(Section1_5);
        uniqueid.add(uid5);
	studList.add(Section1_6);
        uniqueid.add(uid6);
	studList.add(Section1_7);
        uniqueid.add(uid7);
	studList.add(Section1_8);
        uniqueid.add(uid8);
	studList.add(Section1_9);
        uniqueid.add(uid9);
	studList.add(Section1_10);
        uniqueid.add(uid10);
	studList.add(Section1_11);
        uniqueid.add(uid11);
	studList.add(Section1_12);
        uniqueid.add(uid12);
	studList.add(Section1_13);
        uniqueid.add(uid13);
	studList.add(Section1_14);
        uniqueid.add(uid14);
	studList.add(Section1_15);
        uniqueid.add(uid15);
	studList.add(Section1_16);
        uniqueid.add(uid16);
	studList.add(Section1_17);
        uniqueid.add(uid17);
	studList.add(Section1_18);
        uniqueid.add(uid18);
	studList.add(Section1_19);
        uniqueid.add(uid19);
	studList.add(Section1_20);
        uniqueid.add(uid20);
	studList.add(Section1_21);
        uniqueid.add(uid21);
	studList.add(Section1_22);
        uniqueid.add(uid22);
	studList.add(Section1_23);
        uniqueid.add(uid23);
	studList.add(Section1_24);
        uniqueid.add(uid24);
	studList.add(Section1_25);
        uniqueid.add(uid25);
        choices();
    }
}  
